"""
Producer Behavior Polish: Musical realism improvements.

Applies post-generation refinements to ProducerArrangement to make them sound
like a real producer structured them, not just technically correct arrangements.

Focus areas:
1. Hook impact tuning - Hooks feel bigger than verses
2. Verse vocal-space logic - Remove busy melodic layers  
3. Transition polish - Better section connections
4. Final hook expansion - Last hook is equal/bigger than first
5. Variation density rules - Meaningful changes every 4-8 bars
6. Humanization hints - Subtle timing/velocity/density variations
"""

import logging
from typing import List
from app.services.producer_models import (
    ProducerArrangement,
    Section,
    SectionType,
    InstrumentType,
    Variation,
    VariationType,
    Transition,
    TransitionType,
    EnergyPoint,
)

logger = logging.getLogger(__name__)


class ProducerBehaviorPolish:
    """Applies musical refinements to arrangements for increased realism."""

    @staticmethod
    def polish(arrangement: ProducerArrangement) -> ProducerArrangement:
        """
        Apply all polish rules to an arrangement.
        
        Args:
            arrangement: The base ProducerArrangement generated by ProducerEngine
            
        Returns:
            Improved arrangement with enhanced musical properties
        """
        logger.info(f"Polishing arrangement: {len(arrangement.sections)} sections")
        
        # Apply in order: hooks -> verses -> transitions -> variations -> humanization
        arrangement = ProducerBehaviorPolish.tune_hook_impact(arrangement)
        arrangement = ProducerBehaviorPolish.polish_verse_vocal_space(arrangement)
        arrangement = ProducerBehaviorPolish.polish_transitions(arrangement)
        arrangement = ProducerBehaviorPolish.expand_final_hook(arrangement)
        arrangement = ProducerBehaviorPolish.ensure_variation_density(arrangement)
        arrangement = ProducerBehaviorPolish.hint_humanization(arrangement)
        
        return arrangement

    @staticmethod
    def tune_hook_impact(arrangement: ProducerArrangement) -> ProducerArrangement:
        """
        Enhance hook sections to feel bigger and more impactful than verses.
        
        Musical improvements:
        - Hooks have 2-3 more instruments than verses
        - Higher percussion density in hooks (extra hats, fills)
        - Increased energy level for hooks
        - Add additional layers (strings, FX, synth)
        """
        hook_sections = [
            (idx, s) for idx, s in enumerate(arrangement.sections)
            if s.section_type in (SectionType.HOOK, SectionType.CHORUS)
        ]
        
        verse_sections = [
            (idx, s) for idx, s in enumerate(arrangement.sections)
            if s.section_type == SectionType.VERSE
        ]
        
        if not hook_sections or not verse_sections:
            return arrangement
        
        # Analyze current instrument counts
        avg_verse_instruments = (
            sum(len(s[1].instruments) for s in verse_sections) / len(verse_sections)
            if verse_sections else 0
        )
        
        logger.debug(f"Average verse instruments: {avg_verse_instruments:.1f}")
        
        # Boost hooks: add 2-3 more instruments than average verse
        for hook_idx, hook_section in hook_sections:
            current_instruments = set(hook_section.instruments)
            
            # Calculate target instrument count
            target_count = int(avg_verse_instruments) + 2
            
            # Add missing impactful layers
            potential_additions = [
                InstrumentType.PERCUSSION,  # Extra percussion for impact
                InstrumentType.FX,           # Sound design effects
                InstrumentType.STRINGS,      # Harmonic support
                InstrumentType.SYNTH,        # Texture/pad
                InstrumentType.HORN,         # Brassy emphasis
            ]
            
            # Add instruments until we reach target
            for instrument in potential_additions:
                if (
                    len(current_instruments) >= target_count
                    or instrument in current_instruments
                ):
                    continue
                current_instruments.add(instrument)
                logger.debug(f"Adding {instrument.value} to {hook_section.name}")
            
            hook_section.instruments = list(current_instruments)
            
            # Boost energy in hooks
            hook_section.energy_level = min(1.0, hook_section.energy_level + 0.15)
        
        logger.info(f"✓ Hook impact tuned: {len(hook_sections)} hooks enhanced")
        return arrangement

    @staticmethod
    def polish_verse_vocal_space(arrangement: ProducerArrangement) -> ProducerArrangement:
        """
        Create vocal space in verses by removing busy melodic layers.
        
        Musical improvements:
        - Remove LEAD, MELODY layers from verses
        - Keep BASS, KICK, SNARE, HATS (rhythm foundation)
        - Keep PAD if only 1 pad, remove excess pads
        - Preserve STRINGS if minimal
        - Result: verses have 3-5 instruments, mostly rhythm-focused
        """
        verse_sections = [
            (idx, s) for idx, s in enumerate(arrangement.sections)
            if s.section_type == SectionType.VERSE
        ]
        
        if not verse_sections:
            return arrangement
        
        # Instruments to KEEP in verses (vocal-friendly)
        VERSE_ESSENTIAL = {
            InstrumentType.KICK,
            InstrumentType.SNARE,
            InstrumentType.HATS,
            InstrumentType.BASS,
            InstrumentType.CLAP,
        }
        
        # Instruments that can stay but limit to 1
        VERSE_OPTIONAL_SINGLE = {
            InstrumentType.PAD,
            InstrumentType.STRINGS,
        }
        
        # Instruments to REMOVE (busy melodic layer)
        VERSE_REMOVE = {
            InstrumentType.LEAD,
            InstrumentType.MELODY,
            InstrumentType.VOCAL,  # Space for artist vocal
        }
        
        for verse_idx, verse_section in verse_sections:
            current = set(verse_section.instruments)
            
            # Remove busy melodic layers
            current -= VERSE_REMOVE
            
            # Keep if essential
            verse_essential = current & VERSE_ESSENTIAL
            
            # Handle optional singles (keep max 1)
            optional_present = current & VERSE_OPTIONAL_SINGLE
            if len(optional_present) > 1:
                # Keep only one pad/strings
                to_remove = list(optional_present)[1:]
                current -= set(to_remove)
                logger.debug(
                    f"Removing extra optional layers from {verse_section.name}: "
                    f"{[i.value for i in to_remove]}"
                )
            
            # Keep the optional if present
            optional_kept = current & VERSE_OPTIONAL_SINGLE
            
            # Limit total to 5 instruments in verse (tight and vocal-friendly)
            result = verse_essential | optional_kept
            if len(result) > 5:
                # Remove least essential optional
                result = list(result)[:5]
            
            verse_section.instruments = list(result)
            logger.debug(
                f"Verse '{verse_section.name}' instruments simplified to: "
                f"{[i.value for i in verse_section.instruments]}"
            )
        
        logger.info(f"✓ Verse vocal-space polished: {len(verse_sections)} verses optimized")
        return arrangement

    @staticmethod
    def polish_transitions(arrangement: ProducerArrangement) -> ProducerArrangement:
        """
        Enhance transitions between sections with professional production techniques.
        
        Musical improvements:
        - Pre-hook mute (silence 0.5-1 bar before hook entry)
        - Silence drops (dramatic pause before builds)
        - Risers (rising tension into hooks)
        - Snare/drum fills (bridge to hook transitions)
        - Bridge breakdowns (reduce layers)
        - Outro strip-downs (gradual reduction)
        """
        # Enhance existing transitions with more variation
        new_transitions = []
        
        for i, section in enumerate(arrangement.sections[:-1]):
            next_section = arrangement.sections[i + 1]
            
            # Determine optimal transition type
            transition_type = TransitionType.CROSSFADE
            intensity = 0.7
            
            if next_section.section_type in (SectionType.HOOK, SectionType.CHORUS):
                # Pre-hook mute + riser combo
                if section.section_type == SectionType.VERSE:
                    # Verse -> Hook: use silence drop + riser
                    transition_type = TransitionType.SILENCE_DROP
                    intensity = 0.8
                    # Add riser as separate event
                    new_transitions.append(
                        Transition(
                            from_section=i,
                            to_section=i + 1,
                            transition_type=TransitionType.SILENCE_DROP,
                            duration_bars=1,
                            intensity=0.8,
                        )
                    )
                    new_transitions.append(
                        Transition(
                            from_section=i,
                            to_section=i + 1,
                            transition_type=TransitionType.RISER,
                            duration_bars=1,
                            intensity=0.9,
                        )
                    )
                elif section.section_type == SectionType.BRIDGE:
                    # Bridge -> Hook: drum fill + riser
                    new_transitions.append(
                        Transition(
                            from_section=i,
                            to_section=i + 1,
                            transition_type=TransitionType.DRUM_FILL,
                            duration_bars=1,
                            intensity=0.8,
                        )
                    )
                    new_transitions.append(
                        Transition(
                            from_section=i,
                            to_section=i + 1,
                            transition_type=TransitionType.RISER,
                            duration_bars=1,
                            intensity=0.9,
                        )
                    )
                else:
                    # Default to riser for other -> hook
                    transition_type = TransitionType.RISER
                    intensity = 0.85
            
            elif next_section.section_type == SectionType.BRIDGE:
                # -> Bridge: filter sweep (reducing energy feel)
                transition_type = TransitionType.FILTER_SWEEP
                intensity = 0.6
            
            elif next_section.section_type == SectionType.OUTRO:
                # -> Outro: crossfade with strip-down
                transition_type = TransitionType.CROSSFADE
                intensity = 0.5
        
        # Only replace if we added transitions, otherwise keep originals
        if new_transitions:
            arrangement.transitions = new_transitions
            logger.info(f"✓ Transitions polished: {len(new_transitions)} total transitions")
        
        return arrangement

    @staticmethod
    def expand_final_hook(arrangement: ProducerArrangement) -> ProducerArrangement:
        """
        Make the final hook equal or bigger than the first hook.
        
        Musical improvements:
        - Detect first and last hook sections
        - If last hook has fewer instruments, add extras
        - Boost energy of final hook
        - Add variation cues at the end for extra impact
        """
        hook_sections_with_indices = [
            (idx, s) for idx, s in enumerate(arrangement.sections)
            if s.section_type in (SectionType.HOOK, SectionType.CHORUS)
        ]
        
        if len(hook_sections_with_indices) < 2:
            return arrangement
        
        first_hook_idx, first_hook = hook_sections_with_indices[0]
        last_hook_idx, last_hook = hook_sections_with_indices[-1]
        
        first_hook_instrument_count = len(first_hook.instruments)
        last_hook_instrument_count = len(last_hook.instruments)
        
        logger.debug(
            f"First hook has {first_hook_instrument_count} instruments, "
            f"last hook has {last_hook_instrument_count}"
        )
        
        # Expand last hook to match or exceed first hook
        if last_hook_instrument_count < first_hook_instrument_count:
            first_hook_instruments = set(first_hook.instruments)
            last_hook_instruments = set(last_hook.instruments)
            
            # Add missing instruments from first hook
            missing = first_hook_instruments - last_hook_instruments
            for instrument in missing:
                last_hook_instruments.add(instrument)
                logger.debug(
                    f"Adding {instrument.value} to final hook to match first hook"
                )
            
            last_hook.instruments = list(last_hook_instruments)
        
        # Boost final hook energy slightly higher
        first_hook_energy = first_hook.energy_level
        last_hook_energy = last_hook.energy_level
        
        if last_hook_energy <= first_hook_energy:
            last_hook.energy_level = min(1.0, first_hook_energy + 0.05)
            logger.debug(
                f"Boosted final hook energy from {last_hook_energy:.2f} "
                f"to {last_hook.energy_level:.2f}"
            )
        
        logger.info(f"✓ Final hook expanded to match first hook")
        return arrangement

    @staticmethod
    def ensure_variation_density(arrangement: ProducerArrangement) -> ProducerArrangement:
        """
        Ensure meaningful variations every 4-8 bars.
        
        Musical improvements:
        - Check each section for variation frequency
        - Add missing variations to maintain interest
        - Make variations context-aware (verse vs hook vs bridge)
        - Ensure at least one variation per 8 bars
        """
        # Section-specific meaningful variation types
        VARIATION_BY_SECTION = {
            SectionType.VERSE: [
                VariationType.HIHAT_ROLL,
                VariationType.BASS_VARIATION,
                VariationType.VELOCITY_CHANGE,
            ],
            SectionType.HOOK: [
                VariationType.DRUM_FILL,
                VariationType.VELOCITY_CHANGE,
                VariationType.AUTOMATION,
            ],
            SectionType.BRIDGE: [
                VariationType.INSTRUMENT_DROPOUT,
                VariationType.VELOCITY_CHANGE,
                VariationType.AUTOMATION,
            ],
            SectionType.INTRO: [VariationType.VELOCITY_CHANGE],
            SectionType.OUTRO: [VariationType.VELOCITY_CHANGE],
        }
        
        for section_idx, section in enumerate(arrangement.sections):
            # Calculate ideal variation interval (bars)
            ideal_interval = min(8, max(4, section.bars // 2))
            
            # Check current variations
            existing_variation_bars = sorted(
                [v.bar for v in section.variations]
            )
            
            # Add missing variations at ideal intervals
            expected_bars = []
            for bar_offset in range(ideal_interval, section.bars + 1, ideal_interval):
                expected_bars.append(section.bar_start + bar_offset)
            
            # Find missing bars
            missing_bars = set(expected_bars) - set(existing_variation_bars)
            
            # Add variations for missing bars
            variation_types = VARIATION_BY_SECTION.get(
                section.section_type,
                [VariationType.VELOCITY_CHANGE],
            )
            
            for missing_bar in sorted(missing_bars):
                # Rotate through section-specific variations
                variation_type = variation_types[
                    len(section.variations) % len(variation_types)
                ]
                
                new_variation = Variation(
                    bar=missing_bar,
                    section_index=section_idx,
                    variation_type=variation_type,
                    intensity=0.5,
                    description=f"Polished {variation_type.value} in {section.name}",
                )
                section.variations.append(new_variation)
                arrangement.all_variations.append(new_variation)
                
                logger.debug(
                    f"Added {variation_type.value} variation at bar "
                    f"{missing_bar} in {section.name}"
                )
        
        logger.info(
            f"✓ Variation density ensured: "
            f"{len(arrangement.all_variations)} total variations"
        )
        return arrangement

    @staticmethod
    def hint_humanization(arrangement: ProducerArrangement) -> ProducerArrangement:
        """
        Add humanization hints to metadata for render executor to apply.
        
        Musical improvements:
        - Add subtle timing variations per instrument
        - Suggest velocity variations per track
        - Add density variation hints
        - Keep it deterministic for testing
        
        These are stored as metadata/annotations, not changes to the structure.
        """
        # Add humanization hints to arrangement metadata
        if not hasattr(arrangement, "humanization_hints"):
            arrangement.humanization_hints = {}
        
        # Timing variations per instrument type (in ms)
        timing_hints = {
            InstrumentType.KICK: 0,      # Keep kick locked
            InstrumentType.SNARE: 5,     # Subtle swing
            InstrumentType.HATS: 8,      # More swing
            InstrumentType.BASS: 0,      # Keep locked
            InstrumentType.CLAP: 10,     # Loose timing
        }
        
        # Velocity variation range per instrument type
        velocity_hints = {
            InstrumentType.KICK: 2,      # Very tight
            InstrumentType.SNARE: 5,     # Some variation
            InstrumentType.HATS: 8,      # More humanized
            InstrumentType.PERCUSSION: 10,
            InstrumentType.CLAP: 5,
        }
        
        arrangement.humanization_hints = {
            "timing_variations_ms": timing_hints,
            "velocity_variation_range": velocity_hints,
            "density_variation_hint": "Apply subtle swing to hi-hats and light percussion",
        }
        
        logger.info("✓ Humanization hints added (deterministic for testing)")
        return arrangement

    @staticmethod
    def validate_polish_improvements(
        original: ProducerArrangement,
        polished: ProducerArrangement,
    ) -> dict:
        """
        Validate that polish improvements were applied correctly.
        
        Returns:
            Dictionary with improvement metrics and validation status
        """
        improvements = {
            "hook_impact_improved": False,
            "verse_vocal_space_improved": False,
            "transitions_enhanced": False,
            "final_hook_expanded": False,
            "variations_added": False,
            "humanization_hints_present": False,
        }
        
        # Check hook impact
        orig_hooks = [
            s for s in original.sections
            if s.section_type in (SectionType.HOOK, SectionType.CHORUS)
        ]
        polish_hooks = [
            s for s in polished.sections
            if s.section_type in (SectionType.HOOK, SectionType.CHORUS)
        ]
        if orig_hooks and polish_hooks:
            orig_avg_instruments = sum(len(s.instruments) for s in orig_hooks) / len(
                orig_hooks
            )
            polish_avg_instruments = sum(len(s.instruments) for s in polish_hooks) / len(
                polish_hooks
            )
            improvements["hook_impact_improved"] = (
                polish_avg_instruments > orig_avg_instruments
            )
        
        # Check verse vocal space
        orig_verses = [
            s for s in original.sections if s.section_type == SectionType.VERSE
        ]
        polish_verses = [
            s for s in polished.sections if s.section_type == SectionType.VERSE
        ]
        if orig_verses and polish_verses:
            # Verses should have fewer/removed melodic layers
            melodic_instruments = {InstrumentType.LEAD, InstrumentType.MELODY}
            orig_melodic_count = sum(
                1 for s in orig_verses if any(i in s.instruments for i in melodic_instruments)
            )
            polish_melodic_count = sum(
                1 for s in polish_verses if any(i in s.instruments for i in melodic_instruments)
            )
            improvements["verse_vocal_space_improved"] = (
                polish_melodic_count <= orig_melodic_count
            )
        
        # Check transitions
        improvements["transitions_enhanced"] = len(polished.transitions) >= len(
            original.transitions
        )
        
        # Check final hook
        if polish_hooks and len(polish_hooks) >= 2:
            first_count = len(polish_hooks[0].instruments)
            last_count = len(polish_hooks[-1].instruments)
            improvements["final_hook_expanded"] = last_count >= first_count
        
        # Check variations
        improvements["variations_added"] = len(
            polished.all_variations
        ) >= len(original.all_variations)
        
        # Check humanization
        improvements["humanization_hints_present"] = hasattr(
            polished, "humanization_hints"
        ) and polished.humanization_hints
        
        return improvements
