"""
Source Quality Mode — classification and per-mode arrangement constraints.

A *source quality mode* describes where the stems came from and how much
the arranger can trust them for fine-grained role separation.

Modes (in order of decreasing reliability):

    true_stems      — stems uploaded individually by the artist; each file
                      contains exactly one isolated element (kick, snare,
                      bass, lead, etc.).  Full arrangement rule strictness.

    zip_stems       — stems bundled in a ZIP upload; still artist-curated but
                      may contain mixed or ambiguous files.  Moderate strictness.

    ai_separated    — stems generated by on-the-fly AI source separation from
                      a single mixed audio file (e.g. vocals/drums/bass/other).
                      Separation artefacts are common; rule strictness reduced,
                      melodic-role caps lowered, low-end handling made safer,
                      "other" over-stacking avoided.

    stereo_fallback — no usable stem separation; the arrangement uses the
                      full stereo mix as a single source.  Most conservative
                      mode; effectively no layering.

Per-mode constraints are encoded in ``SOURCE_QUALITY_PROFILES`` and applied
in ``arrangement_jobs.py`` when selecting section stem-role layers.

Integration points:
    - arrangement_jobs.py   → _select_section_stem_roles() uses the profile
                              when source_quality is set on the job params.
    - render_qa.py          → QA gates factor source confidence into scoring.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum


class SourceQualityMode(str, Enum):
    """Classification of where arrangement stems originate from."""

    TRUE_STEMS = "true_stems"
    ZIP_STEMS = "zip_stems"
    AI_SEPARATED = "ai_separated"
    STEREO_FALLBACK = "stereo_fallback"


@dataclass(frozen=True)
class SourceQualityProfile:
    """Per-mode limits applied to the arrangement layer selector.

    All attributes are *maxima* or *strictness* knobs — they never override
    the user's own explicit choices, only constrain the automatic logic.
    """

    # Maximum simultaneous melodic roles (melody/harmony/pads/vocal)
    max_melodic_layers: int

    # Maximum simultaneous layers in intro and verse sections
    max_intro_verse_layers: int

    # Maximum simultaneous layers in breakdown / bridge sections
    max_breakdown_layers: int

    # Maximum total simultaneous layers in any non-hook section
    max_layers_non_hook: int

    # Maximum total simultaneous layers in hook section
    max_layers_hook: int

    # Whether to merge ambiguous roles into a single "grouped" representative
    # (e.g. treat all AI "other" stems as a single "synth" or "pads" role)
    group_ambiguous_roles: bool

    # Whether to apply stronger low-end safety (suppress stacking bass + other)
    safe_low_end: bool

    # Minimum Jaccard contrast required between verse and hook role sets
    # (0.0 = no requirement;  higher = require more distinction)
    min_verse_hook_contrast: float

    # Human-readable description used in logs and QA reports
    description: str

    # Confidence weight applied when computing source_confidence QA score (0–1)
    confidence_weight: float


SOURCE_QUALITY_PROFILES: dict[SourceQualityMode, SourceQualityProfile] = {
    SourceQualityMode.TRUE_STEMS: SourceQualityProfile(
        max_melodic_layers=4,
        max_intro_verse_layers=3,
        max_breakdown_layers=2,
        max_layers_non_hook=4,
        max_layers_hook=5,
        group_ambiguous_roles=False,
        safe_low_end=False,
        min_verse_hook_contrast=0.20,
        description="Artist-uploaded individual stems; full rule strictness.",
        confidence_weight=1.0,
    ),
    SourceQualityMode.ZIP_STEMS: SourceQualityProfile(
        max_melodic_layers=3,
        max_intro_verse_layers=3,
        max_breakdown_layers=2,
        max_layers_non_hook=4,
        max_layers_hook=5,
        group_ambiguous_roles=False,
        safe_low_end=False,
        min_verse_hook_contrast=0.20,
        description="Artist-uploaded ZIP bundle; moderate strictness.",
        confidence_weight=0.85,
    ),
    SourceQualityMode.AI_SEPARATED: SourceQualityProfile(
        max_melodic_layers=2,          # conservative: AI melodic bleeds badly
        max_intro_verse_layers=2,      # sparser intros and verses
        max_breakdown_layers=1,        # strong breakdown subtraction
        max_layers_non_hook=2,         # keep non-hook sections lean
        max_layers_hook=3,             # even hook capped lower than true_stems
        group_ambiguous_roles=True,    # collapse noisy sub-roles
        safe_low_end=True,             # avoid bass + other stacking
        min_verse_hook_contrast=0.30,  # require clearer verse→hook distinction
        description=(
            "AI source-separated stems; conservative limits — separation "
            "artefacts degrade precision and reward sparsity."
        ),
        confidence_weight=0.55,
    ),
    SourceQualityMode.STEREO_FALLBACK: SourceQualityProfile(
        max_melodic_layers=1,
        max_intro_verse_layers=1,
        max_breakdown_layers=1,
        max_layers_non_hook=1,
        max_layers_hook=1,
        group_ambiguous_roles=True,
        safe_low_end=True,
        min_verse_hook_contrast=0.0,  # only one role anyway
        description="No stems; stereo-mix fallback; minimal layering.",
        confidence_weight=0.25,
    ),
}


def get_source_quality_profile(mode: SourceQualityMode | str | None) -> SourceQualityProfile:
    """Return the ``SourceQualityProfile`` for *mode*, defaulting to ``TRUE_STEMS``.

    Accepts a ``SourceQualityMode`` enum value or a plain string (e.g.
    ``"ai_separated"``).  Unknown strings fall back to ``TRUE_STEMS`` so
    callers never receive ``None``.
    """
    if mode is None:
        return SOURCE_QUALITY_PROFILES[SourceQualityMode.TRUE_STEMS]
    if isinstance(mode, SourceQualityMode):
        return SOURCE_QUALITY_PROFILES.get(mode, SOURCE_QUALITY_PROFILES[SourceQualityMode.TRUE_STEMS])
    try:
        resolved = SourceQualityMode(str(mode).strip().lower())
        return SOURCE_QUALITY_PROFILES[resolved]
    except ValueError:
        return SOURCE_QUALITY_PROFILES[SourceQualityMode.TRUE_STEMS]


def classify_source_quality(
    *,
    has_true_stems: bool = False,
    stems_from_zip: bool = False,
    stems_from_ai_separation: bool = False,
) -> SourceQualityMode:
    """Classify the source quality mode from ingestion signals.

    Priority order: true_stems > zip_stems > ai_separated > stereo_fallback.

    Args:
        has_true_stems: The user uploaded individual stem files directly.
        stems_from_zip: The stems were extracted from a ZIP archive upload.
        stems_from_ai_separation: The stems were produced by on-the-fly AI
            source-separation from a single mixed file.

    Returns:
        The most specific ``SourceQualityMode`` for the given signals.
    """
    if has_true_stems:
        return SourceQualityMode.TRUE_STEMS
    if stems_from_zip:
        return SourceQualityMode.ZIP_STEMS
    if stems_from_ai_separation:
        return SourceQualityMode.AI_SEPARATED
    return SourceQualityMode.STEREO_FALLBACK
