#!/usr/bin/env python
"""
Migration helper script to safely upgrade the database schema.
This script generates an Alembic autogenerated migration and applies it.
"""

import os
import sys
import subprocess
from pathlib import Path

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent))

from app.config import settings
from app.db import engine
from app.models.test_model import Base
from sqlalchemy import inspect, text

def get_current_schema():
    """Get the current database schema."""
    inspector = inspect(engine)
    tables = inspector.get_table_names()
    
    print("\n" + "="*60)
    print("📊 CURRENT DATABASE SCHEMA")
    print("="*60)
    
    for table_name in sorted(tables):
        columns = inspector.get_columns(table_name)
        print(f"\n📋 Table: {table_name}")
        for col in columns:
            nullable = "NULL" if col['nullable'] else "NOT NULL"
            print(f"   - {col['name']:<20} {str(col['type']):<20} {nullable}")
    
    return tables

def get_expected_schema():
    """Get the expected schema from SQLAlchemy models."""
    print("\n" + "="*60)
    print("🎯 EXPECTED SCHEMA (from SQLAlchemy models)")
    print("="*60)
    
    for table_name, table in Base.metadata.tables.items():
        print(f"\n📋 Table: {table_name}")
        for col in table.columns:
            nullable = "NULL" if col.nullable else "NOT NULL"
            print(f"   - {col.name:<20} {str(col.type):<20} {nullable}")

def check_loops_table():
    """Check if loops table has the required columns."""
    inspector = inspect(engine)
    
    if "loops" not in inspector.get_table_names():
        print("\n⚠️  Table 'loops' does not exist yet")
        return False
    
    columns = {col['name'] for col in inspector.get_columns('loops')}
    required_cols = {
        'id', 'name', 'filename', 'file_url', 'title', 'bpm',
        'musical_key', 'genre', 'duration_seconds', 'created_at'
    }
    
    missing = required_cols - columns
    if missing:
        print(f"\n❌ Missing columns in 'loops' table: {', '.join(sorted(missing))}")
        return False
    
    print("\n✅ All required columns present in 'loops' table")
    return True

def generate_migration(message="auto"):
    """Generate an autodetected migration."""
    print(f"\n🔄 Generating migration with message: '{message}'")
    result = subprocess.run(
        [sys.executable, "-m", "alembic", "revision", "--autogenerate", "-m", message],
        cwd=str(Path(__file__).parent),
        capture_output=True,
        text=True
    )
    
    if result.returncode != 0:
        print(f"❌ Migration generation failed:\n{result.stderr}")
        return False
    
    print(f"✅ Migration generated:\n{result.stdout}")
    return True

def apply_migrations():
    """Apply pending migrations."""
    print("\n⬆️  Applying migrations...")
    result = subprocess.run(
        [sys.executable, "-m", "alembic", "upgrade", "head"],
        cwd=str(Path(__file__).parent),
        capture_output=True,
        text=True
    )
    
    if result.returncode != 0:
        print(f"❌ Migration application failed:\n{result.stderr}")
        return False
    
    print(f"✅ Migrations applied:\n{result.stdout}")
    return True

def main():
    """Main migration workflow."""
    print("\n╔═══════════════════════════════════════════════════════════╗")
    print("║       LoopArchitect Database Schema Migration            ║")
    print("╚═══════════════════════════════════════════════════════════╝")
    print(f"\n🔗 Database: {settings.database_url[:50]}...")
    
    # Step 1: Get current schema
    current_tables = get_current_schema()
    
    # Step 2: Get expected schema
    get_expected_schema()
    
    # Step 3: Check loops table specifically
    loops_ok = check_loops_table()
    
    # Step 4: Generate migration
    if not generate_migration("add missing loop columns"):
        print("\n⚠️  Could not generate migration")
        return False
    
    # Step 5: Apply migrations
    if not apply_migrations():
        print("\n⚠️  Could not apply migrations")
        return False
    
    # Step 6: Verify
    print("\n" + "="*60)
    print("✅ VERIFICATION")
    print("="*60)
    if check_loops_table():
        print("\n🎉 Database schema is now up to date!")
        return True
    else:
        print("\n⚠️  Schema verification failed")
        return False

if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)
