[phases.build]
  nixPkgs = ['nginx']

[phases.run]
  nginx = 'nginx -g "daemon off;"'
  cmds = ['nginx']

[languages.python]
  version = "3.12"

[staticAssets]
  mountPath = "/static"

[nginx]
  clientMaxBodySize = "200M"
