"""Add render jobs tracking table

Revision ID: 80dcd1ed7522
Revises: beb724ce4e72
Create Date: 2026-03-01 12:59:05.433550

NOTE: This migration is intentionally idempotent.  If the ``render_jobs``
table was already created outside Alembic (e.g. via SQLAlchemy ``create_all()``
during an earlier dev startup), the ``CREATE TABLE`` step is skipped.
The index creation steps are also guarded so that a re-run after a partial
apply does not raise ``DuplicateTable`` or ``DuplicateObject`` errors.

One-time fix for a production database whose ``alembic_version`` row is
behind the actual schema:

    alembic stamp head

That records all migrations as applied without re-running DDL.
"""
import logging
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect

logger = logging.getLogger(__name__)

# revision identifiers, used by Alembic.
revision: str = '80dcd1ed7522'
down_revision: Union[str, Sequence[str], None] = 'beb724ce4e72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema (idempotent: skips DDL that has already been applied)."""
    conn = op.get_bind()
    inspector = inspect(conn)

    if 'render_jobs' not in inspector.get_table_names():
        op.create_table(
            'render_jobs',
            sa.Column('id', sa.String(36), nullable=False),
            sa.Column('loop_id', sa.Integer(), nullable=False),
            sa.Column('job_type', sa.String(50), nullable=False),
            sa.Column('status', sa.String(20), nullable=False, server_default='queued'),
            sa.Column('progress', sa.Integer(), nullable=False, server_default='0'),
            sa.Column('progress_message', sa.String(255), nullable=True),
            sa.Column('params_json', sa.Text(), nullable=False),
            sa.Column('output_files_json', sa.Text(), nullable=True),
            sa.Column('error_message', sa.Text(), nullable=True),
            sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0'),
            sa.Column('dedupe_hash', sa.String(64), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('started_at', sa.DateTime(), nullable=True),
            sa.Column('finished_at', sa.DateTime(), nullable=True),
            sa.Column('expires_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['loop_id'], ['loops.id'], ),
            sa.PrimaryKeyConstraint('id')
        )

    try:
        op.create_index(
            'ix_render_jobs_loop_dedupe_created',
            'render_jobs',
            ['loop_id', 'dedupe_hash', 'created_at'],
            unique=False
        )
    except (sa.exc.OperationalError, sa.exc.ProgrammingError) as exc:
        logger.warning(
            "Could not create index ix_render_jobs_loop_dedupe_created "
            "(may already exist): %s", exc
        )

    try:
        op.create_index(
            'ix_render_jobs_status',
            'render_jobs',
            ['status'],
            unique=False
        )
    except (sa.exc.OperationalError, sa.exc.ProgrammingError) as exc:
        logger.warning(
            "Could not create index ix_render_jobs_status "
            "(may already exist): %s", exc
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_render_jobs_status', table_name='render_jobs')
    op.drop_index('ix_render_jobs_loop_dedupe_created', table_name='render_jobs')
    op.drop_table('render_jobs')
    # ### end Alembic commands ###
