"""Add render jobs tracking table

Revision ID: 80dcd1ed7522
Revises: beb724ce4e72
Create Date: 2026-03-01 12:59:05.433550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80dcd1ed7522'
down_revision: Union[str, Sequence[str], None] = 'beb724ce4e72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    from sqlalchemy import inspect as sa_inspect
    conn = op.get_bind()
    inspector = sa_inspect(conn)
    existing_tables = set(inspector.get_table_names())

    if 'render_jobs' not in existing_tables:
        op.create_table(
            'render_jobs',
            sa.Column('id', sa.String(36), nullable=False),
            sa.Column('loop_id', sa.Integer(), nullable=False),
            sa.Column('job_type', sa.String(50), nullable=False),
            sa.Column('status', sa.String(20), nullable=False, server_default='queued'),
            sa.Column('progress', sa.Integer(), nullable=False, server_default='0'),
            sa.Column('progress_message', sa.String(255), nullable=True),
            sa.Column('params_json', sa.Text(), nullable=False),
            sa.Column('output_files_json', sa.Text(), nullable=True),
            sa.Column('error_message', sa.Text(), nullable=True),
            sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0'),
            sa.Column('dedupe_hash', sa.String(64), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('started_at', sa.DateTime(), nullable=True),
            sa.Column('finished_at', sa.DateTime(), nullable=True),
            sa.Column('expires_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['loop_id'], ['loops.id'], ),
            sa.PrimaryKeyConstraint('id')
        )

    # Create indexes only if they don't exist yet
    existing_indexes = {idx['name'] for idx in inspector.get_indexes('render_jobs')} if 'render_jobs' in existing_tables else set()
    if 'ix_render_jobs_loop_dedupe_created' not in existing_indexes:
        try:
            op.create_index(
                'ix_render_jobs_loop_dedupe_created',
                'render_jobs',
                ['loop_id', 'dedupe_hash', 'created_at'],
                unique=False
            )
        except Exception:
            pass
    if 'ix_render_jobs_status' not in existing_indexes:
        try:
            op.create_index(
                'ix_render_jobs_status',
                'render_jobs',
                ['status'],
                unique=False
            )
        except Exception:
            pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_render_jobs_status', table_name='render_jobs')
    op.drop_index('ix_render_jobs_loop_dedupe_created', table_name='render_jobs')
    op.drop_table('render_jobs')
    # ### end Alembic commands ###
