"""Step D: storage + pipeline updates

Revision ID: beb724ce4e72
Revises: 006_add_bars_column
Create Date: 2026-02-25 15:52:50.636759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beb724ce4e72'
down_revision: Union[str, Sequence[str], None] = '006_add_bars_column'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loops_id'), table_name='loops')
    op.drop_table('loops')
    op.drop_index(op.f('idx_arrangement_loop_status'), table_name='arrangements')
    op.drop_index(op.f('ix_arrangements_id'), table_name='arrangements')
    op.drop_index(op.f('ix_arrangements_loop_id'), table_name='arrangements')
    op.drop_table('arrangements')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arrangements',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('loop_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('target_seconds', sa.INTEGER(), nullable=False),
    sa.Column('genre', sa.VARCHAR(), nullable=True),
    sa.Column('intensity', sa.VARCHAR(), nullable=True),
    sa.Column('include_stems', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('output_file_url', sa.VARCHAR(), nullable=True),
    sa.Column('stems_zip_url', sa.VARCHAR(), nullable=True),
    sa.Column('arrangement_json', sa.TEXT(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('output_s3_key', sa.VARCHAR(), nullable=True),
    sa.Column('output_url', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['loop_id'], ['loops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arrangements_loop_id'), 'arrangements', ['loop_id'], unique=False)
    op.create_index(op.f('ix_arrangements_id'), 'arrangements', ['id'], unique=False)
    op.create_index(op.f('idx_arrangement_loop_status'), 'arrangements', ['loop_id', 'status'], unique=False)
    op.create_table('loops',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('tempo', sa.FLOAT(), nullable=True),
    sa.Column('key', sa.VARCHAR(), nullable=True),
    sa.Column('genre', sa.VARCHAR(), nullable=True),
    sa.Column('file_url', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('bpm', sa.INTEGER(), server_default=sa.text('(NULL)'), nullable=True),
    sa.Column('duration_seconds', sa.FLOAT(), server_default=sa.text('(NULL)'), nullable=True),
    sa.Column('filename', sa.VARCHAR(), server_default=sa.text('(NULL)'), nullable=True),
    sa.Column('musical_key', sa.VARCHAR(), server_default=sa.text('(NULL)'), nullable=True),
    sa.Column('title', sa.VARCHAR(), server_default=sa.text('(NULL)'), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('processed_file_url', sa.VARCHAR(), nullable=True),
    sa.Column('analysis_json', sa.TEXT(), nullable=True),
    sa.Column('file_key', sa.VARCHAR(), nullable=True),
    sa.Column('bars', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loops_id'), 'loops', ['id'], unique=False)
    # ### end Alembic commands ###
